### ISSUE TITLE
`delete-application` remove the `--project-path` flag.

### ISSUE THREAD

**Issue by ppittle** [aws/aws-dotnet-deploy#125]
## The Question
Can the `--project-path` for the `delete-application` command be removed?  Think it used to be a way to read the `PreviousDeploymentSettings` via **aws-netsuite-deployment.json** to find the region an application was deployed to.  

But use of the **aws-netsuite-deployment.json** file has been removed, so don't think this flag makes sense anymore.

#### Bonus
Can `PreviousDeploymentSettings` class also be removed?

![image](https://user-images.githubusercontent.com/1190907/110887814-d4691700-829f-11eb-9211-411a2b296a03.png)

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] `0.1.1-beta.20210312012242.78ce3cc`
 - Include the output of `dotnet --info` `5.0.201`
 - OS Info: `Windows 10`

---

This is a :question: general question

**Comment by philasmar** [comment]
The --project-path is still used as it allows the update of the last deployed stack settings file.
