### ISSUE TITLE
Persist custom settings so can retry if deploy fails

### ISSUE THREAD

**Issue by ppittle** [aws/aws-dotnet-deploy#147]
**Is your feature request related to a problem? Please describe.**
Save the current settings locally in the event the cdk deploy fails so that I don't have to re-enter them to retry the deployment.

**Describe the solution you'd like**
save to a temp file until confirming that settings have been saved in Cloud Formation metadata?

---

This is a :rocket: feature request

**Comment by philasmar** [comment]
Settings are saved in CloudFormation after the first successful deployment.
