### ISSUE TITLE
perf: Redeploy hangs after displaying configuration

### ISSUE THREAD

**Issue by ppittle** [aws/aws-dotnet-deploy#151]
**Describe the bug**
When redeploying, the tool will hang after displaying the deployed settings but before displaying the list of settings that can be customized:

(gif is about 60 seconds long.  Hang is from 0:10 - 0:55)

![redeployPerf](https://user-images.githubusercontent.com/1190907/111365506-ccb6c300-864f-11eb-84e9-5630a7d7342d.gif)

**To Reproduce**
1. Deploy to asp.net mvc app using Fargate Web recipe
2. Run `dotnet aws deploy` again and select previously deployed application

**Expected behavior**
Tool should not hang before displaying settings that can be customized.

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] `0.1.1-beta.20210315205437.06db70a`
 - Include the output of `dotnet --info` `5.0.201`
 - OS Info: `Windows 10`

---

This is a :bug: bug report

**Comment by ganeshnj** [comment]
We should block the input (except cancel operation ex. Ctrl+C), when the CLI is doing background processing so that no unexpected things happen due to stdin provided.

**Comment by ashishdhingra** [comment]
Not reproducible in version `1.10.4`.
