### ISSUE TITLE
Redeploy: DeploymentBundle Settings are lost 

### ISSUE THREAD

**Issue by ppittle** [aws/aws-dotnet-deploy#153]
**Describe the bug**
DeploymnetBundle Settings like `DotnetPublishBuildConfiguration` and `DotnetPublishAdditionalBuildArguments` in Elastic Beanstalk recipe and `DockerBuildArgs` in Fargate deployments are not persisted.  When doing a redeploy, you have to re-endter these values.

**To Reproduce**
1. In a web project run `dotnet aws deploy`. 
2. Select Beanstalk
3. Customize the `DotnetPublishAdditionalBuildArguments`: `"/p:DefineConstants=TEST"`
4. Deploy
5. Run `dotnet aws deploy`. 
6. Select previously deployed stack
7. Notice that `DotnetPublishAdditionalBuildArguments` is blank.

**Expected behavior**
`DotnetPublishAdditionalBuildArguments`  should have value  `"/p:DefineConstants=TEST"`

**Screenshots**
![image](https://user-images.githubusercontent.com/1190907/111376271-7c922d80-865c-11eb-8063-f451e2b63434.png)

![image](https://user-images.githubusercontent.com/1190907/111376329-8caa0d00-865c-11eb-9f6e-bb837d64bea4.png)

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] `0.1.1-beta.20210315205437.06db70a`
 - Include the output of `dotnet --info` `5.0.201`
 - OS Info: `Windows 10`

**Additional context**

---

This is a :bug: bug report

**Comment by ashishdhingra** [comment]
Appears to be fixed in version `1.10.4`:
```
Current settings (select number to change its value)
----------------------------------------------------
1 . EC2 Instance Type: 
2 . Beanstalk Platform: arn:aws:elasticbeanstalk:us-east-1::platform/.NET Core running on 64bit Amazon Linux 2/2.5.0
3 . Managed Platform Updates: 
	Enable Managed Platform Updates: True
	Preferred Start Time: Sun:00:00
	Update Level: minor
4 . Enable AWS X-Ray Tracing Support: False
5 . Reverse Proxy: nginx
6 . Environment Variables: 
7 . Virtual Private Cloud (VPC): 
	Use a VPC : False
8 . Dotnet Build Configuration: Release
9 . Dotnet Publish Args: /p:DefineConstants=TEST
10. Self Contained Build: False
```
