### ISSUE TITLE
The filename for Dockefile used should be configurable.

### ISSUE THREAD

**Issue by normj** [aws/aws-dotnet-deploy#155]
**Describe the bug**
Currently the tool is hardcoded to use `Dockerfile` for the Dockerfile to pass to docker build. Although that is most common it is not uncommon to use a different file name for different scenarios. Imagine a project having `Dockerfile.local` and Dockerfile.aws`. 

The tool should allow customizing the name of the Dockerfile passed into docker build.
---

This is a :bug: bug report

**Comment by ericis** [comment]
@ganeshnj and @normj suggest that this allow for an entire path override and not just the file name. Our project stored this file under "./docker/Dockerfile". This alternative path outside of the root was necessary for other tooling.

**Comment by ashovlin** [comment]
This was addressed by https://github.com/aws/aws-dotnet-deploy/pull/509, which was released in [0.46.16](https://github.com/aws/aws-dotnet-deploy/releases/tag/0.46.16).
