### ISSUE TITLE
ECS Fargate deployment deletion leaves behind the ECR repository and image

### ISSUE THREAD

**Issue by ganeshnj** [aws/aws-dotnet-deploy#161]
**Describe the bug**
On deletion of a ECS Fargate deployment, ECR image used for the deployment stays as it is.

**To Reproduce**
1. `dotnet new webapp -n "MyWebApp"`
2. `cd MyWebApp`
3. `dotnet aws deploy`
4. deploy with default configuration
5. `dotnet aws delete-deployment MyWebApp`
6. Observe ECR image used for MyWebApp

**Logs**
N/A

**Expected behavior**
Corresponding ECR image and repository (if created with deployment) must be deleted on deletion of the deployment.

**Screenshots**
N/A

**Screen recording**
N/A

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0]  0.4.2
 - Include the output of `dotnet --info`
 - OS Info:  All

**Additional context**

---

This is a :bug: bug report

**Comment by philasmar** [comment]
As discussed in the linked PR, this could potentially delete customer data and that is an unwanted behavior.
