### ISSUE TITLE
Mock the Path class to support unit testing

### ISSUE THREAD

**Issue by philasmar** [aws/aws-dotnet-deploy#182]
**Describe the bug**
Mock the Path class to support unit testing

**Expected behavior**
Instantiate an instance of the Path class that we can mock

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] 0.4.2
 - Include the output of `dotnet --info`
 - OS Info: 

**Additional context**

---

This is a :bug: bug report

**Comment by ashishdhingra** [comment]
Closing based on update.
