### ISSUE TITLE
deploy argument for "Choose deployment option"

### ISSUE THREAD

**Issue by ericis** [aws/aws-dotnet-deploy#403]
**Is your feature request related to a problem? Please describe.**

It seems it is not possible to automate "deploy", because of the "Choose deployment option" prompt (e.g. choosing between "ASP.NET Core App to Amazon ECS using Fargate" or "ASP.NET Core App to AWS App Runner").

**Describe the solution you'd like**

Add a command argument, like "--deployment" with named options:

`dotnet dotnet-aws deploy --deployment AppRunner ...`

**Describe alternatives you've considered**

It is possible to pipe the answer into the CLI prompt, but this is not a reliable solution.

**Additional context**

Similar to #404

---

This is a :rocket: feature request

**Comment by philasmar** [comment]
The deploy tool supports using configuration files to automate deployments. 
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/deployment-tool-config-file.html

You will be able to specify the RecipeId in the file and launch the deploy tool using the configuration file. 
`dotnet aws deploy --apply <path-to-config-file>`
