### ISSUE TITLE
No "--force" argument to automate delete

### ISSUE THREAD

**Issue by ericis** [aws/aws-dotnet-deploy#404]
**Is your feature request related to a problem? Please describe.**

Automating `dotnet dotnet-aws delete-deployment` does not offer an argument to force delete and avoid the interactive confirmation prompt of "Are you sure you want to delete ...?"

**Describe the solution you'd like**

Add the argument `--force` and `-f` to improve automation reliability.

**Describe alternatives you've considered**

The workaround `echo "y" | dotnet dotnet-aws delete-deployment ...` is possible, but fragile since the use of piping "y" isn't explicit.

**Additional context**

Similar to #403

---

This is a :rocket: feature request

**Comment by 96malhar** [comment]
@ericis Thank you for trying out our tooling and providing feedback.

We added the functionality to delete applications without any user prompts as part of https://github.com/aws/aws-dotnet-deploy/pull/445. 

Closing this issue as it has been resolved.
