### ISSUE TITLE
Elastic Beanstalk support for .NET 6

### ISSUE THREAD

**Issue by bobskigit** [aws/aws-dotnet-deploy#413]
When will AWS ship the default gravitron instances on Elastic beanstalk with .NET 6 support?

In fact when will all the Elastic beanstalks have .NET 6 runtime support?

**Comment by gloriousjob** [comment]
Back in March 31, .NET 6.0.3 was supported.
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-dotnetlinux.html

You can select Graviton instances when you configure, assuming you're using an arm64 instance.

**Comment by philasmar** [comment]
As far as this project is related, we have added support to .NET 6 for Elastic Beanstalk deployments.
