### ISSUE TITLE
Publish my application to ECR

### ISSUE THREAD

**Issue by awschristou** [aws/aws-dotnet-deploy#431]
**Is your feature request related to a problem? Please describe.**
I would like to use the deploy tool to publish my application to an image in ECR, without creating ECS Tasks or Services.
We have received requests for this feature in the AWS Toolkit for Visual Studio through the in-tool feedback feature, and on GitHub - https://github.com/aws/aws-toolkit-visual-studio/issues/211

**Describe the solution you'd like**
I should have an option in the deploy tool to publish my application as an image into ECR. Both from the command line and from the AWS Toolkit's Publish to AWS experience.

---

This is a :rocket: feature request

**Comment by 96malhar** [comment]
A draft PR for this workflow - https://github.com/aws/aws-dotnet-deploy/pull/460

**Comment by philasmar** [comment]
This feature has been released
