### ISSUE TITLE
Generate cloudformation files to further customise the deployed cloudformation stack

### ISSUE THREAD

**Issue by wmundev** [aws/aws-dotnet-deploy#461]
**Is your feature request related to a problem? Please describe.**
Unable to further customize the stack like changing the deployed application load balancer to dualstack from ipv4 for example

**Describe the solution you'd like**
I would like to see the ability to generate an cdk project or a cloudformation project so that i can further customise the deployed resources for my dotnet app that gets deployed using this tool. as far as i can see, i am unable to customise the stack further, for example, i want to update the deployed load balancer to dualstack but am unable to do it in code currently or can't use the tool to achieve this.

**Describe alternatives you've considered**
Manually edit the load balancer in the AWS console, which works fine but the edit does not tie back to the cloudformation stack that gets generated using this deploy tool

**Additional context**
I am loving this tool so far but would love an option to generate a cdk project or cloudformation project so that i can continue using this tool instead of once off deploying my dotnet app and being unable to customise certain resources within the deployed resources.

---

This is a :rocket: feature request

**Comment by philasmar** [comment]
We do have the ability to generate the CDK deployment project and use that project for deployment. This would support the use case you mentioned. This is the documentation for that https://aws.github.io/aws-dotnet-deploy/docs/project/.
