### ISSUE TITLE
Name generation reverses suffixed digits and fails over 100

### ISSUE THREAD

**Issue by floralph** [aws/aws-dotnet-deploy#507]
**Describe the bug**
I have a project suffixed with a year, WebApplication2022.  When opening "Publish to AWS" in the AWS Toolkit for Visual Studio I get the error:  "Failed to generate a valid and unique name."  This occurs when [DeploymentController.StartDeploymentSession line 102](https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.CLI/ServerMode/Controllers/DeploymentController.cs#L102) is called on the server.  

The first issue appears to be a bug.  The logic in [CloudApplicationNameGenerator.GenerateValidName line 75](https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.Orchestration/Utilities/CloudApplicationNameGenerator.cs#L75) reverses the order of any suffixed digits.  For example, WebApplication2022 results in the value 2202 in the suffix variable.

The second issue is that [CloudApplicationNameGenerator.GenerateValidName line 81](https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.Orchestration/Utilities/CloudApplicationNameGenerator.cs#L81) limits the suffix to less than 100.  In the case of a simple incremented suffix at the end of the project name, this would likely work just fine.  If a project name has a number at the end (say a year or maybe just part of the product name like T-1000) the current solution is far too limiting.  If the 100 limit in the while loop is simply to prevent a long running loop, consider a suffix + 100 offset value rather than fixed at cardinal 100.

**To Reproduce**
1. Create a Visual Studio project (an ASP.NET Core Web App template will work) with a number (when reversed until the first bug is fixed) at the end, e.g. WebApplication2022.
2. Right-click the open project in Visual Studio and select Publish to AWS (the AWS Toolkit for Visual Studio must be installed).
3. Wait for the publishing document to open and the error will appear.

**Expected behavior**
Any positive integer suffix that safely fits within an Int32 or Int64 that can be incremented to be less than or equal to that Intxx.MaxValue should just work.  Whatever the numeric suffix of the original project name is, it should keep its fidelity and not be reversed (i.e. 2022 should remain 2022, not reversed to 2202).

**Screenshots**
![image](https://user-images.githubusercontent.com/53063963/163451807-44cc96b7-1ecb-4960-a18e-a44c6f1e708e.png)

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] 0.39.8
 - Include the output of `dotnet --info`
 - OS Info: Windows 10 -->

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---

This is a :bug: bug report

**Comment by philasmar** [comment]
The fix was released.
