### ISSUE TITLE
Using a variable for the TargetFramework property fails to generate recommendations

### ISSUE THREAD

**Issue by 96malhar** [aws/aws-dotnet-deploy#550]
**Describe the bug**
No recommendations are generated when the project `.csproj` file uses a variable for the `TargetFramework` property.

**To Reproduce**
1. Create a new ASP.NET Core web app
2. Replace the `TargetFramework` property group with the following
    
```
<PropertyGroup>
    <TargetFrameworkVersion>net5.0</TargetFrameworkVersion>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
</PropertyGroup>
```
3. Perform a deployment using `dotnet aws deploy --project-path <projectpath>`
4. No recommendations will be generated for the project.

**Expected behavior**
Correct recommendations should be generated even when using a variable for the `TargetFramework` property.

---

This is a :bug: bug report

**Comment by normj** [comment]
This is still an issue. We should have the tool do a first attempt of determining MSBuild parameters by using the `dotnet msbuild <project> -getproperty:<targetframework>` and if that fails fallback to the XML parsing.

This is similar to what the .NET Lambda tools do for determining output type. https://github.com/aws/aws-extensions-for-dotnet-cli/blob/2e5f84b59dfdb05eae42c76d7cb56b197549a6cc/src/Amazon.Common.DotNetCli.Tools/Utilities.cs#L223

**Comment by ashishdhingra** [comment]
Based on discussion with team, closing this issue since we already have a backlog for it (there are no reactions from community as well).
