### ISSUE TITLE
Tooling will not open

### ISSUE THREAD

**Issue by augspurgerr** [aws/aws-dotnet-deploy#610]
![image](https://user-images.githubusercontent.com/24643824/173410639-c0ab247a-4d22-4460-bbe5-2c6228faa3b6.png)

I right click to "Publish to AWS (Preview Feature)" and receive this error.

**Comment by philasmar** [comment]
Is there another process that is running on port 10000?

**Comment by ashishdhingra** [comment]
@augspurgerr I was going through the issue backlog and came across this issue. Please confirm if the issue is fixed for you and could be closed.

Thanks,
Ashish
