### ISSUE TITLE
Specifying Project Path with WSL Path Fails

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-dotnet-deploy#628]
**Describe the bug**
Specifying a `--project-path` from Windows with a WSL path fails

```
dotnet aws deploy --project-path \\\\wsl$\\Ubuntu\\home\\path\\to\\project.csproj

Failed to find a valid .csproj or .fsproj file at path \\\\wsl$\\Ubuntu\\home\\path\\to\\project.csproj
```

Originally reported via the VS Toolkit - https://github.com/aws/aws-toolkit-visual-studio/issues/263

**Expected behavior**
Not entirely sure if this is expected to work. Per https://github.com/aws/aws-dotnet-deploy/pull/311 we're determining paths that start with `\\` are invalid, but looks like this was to prevent SMB shared paths, not necessarily WSL.

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] 0.47.26
 - Include the output of `dotnet --info`

---

This is a :bug: bug report

**Comment by ashishdhingra** [comment]
WSL path has pattern as `\\wsl$\[distro name]`. So essentially, if deployment is expected to happen from a WSL path, then the check [here](https://github.com/aws/aws-dotnet-deploy/blob/29630532fff0d9219f416a38fadd9c778e066efa/src/AWS.Deploy.Common/Utilities/PathUtilities.cs#L18) should be modified to exclude `\\wsl$` path.

**Comment by ashishdhingra** [comment]
Per discussion with team, it's fine to close this issue since it is already in the backlog (there are no reactions from community as well).
