### ISSUE TITLE
Deploy fails to get credentials with SSO profile

### ISSUE THREAD

**Issue by Aracron** [aws/aws-dotnet-deploy#675]
### Describe the bug

When attempting to deploy via the command line, the tool fails to get the credentials for an SSO profile, and is unable to proceed.

### Expected Behavior

The tool should be able to deploy with SSO profiles.

### Current Behavior

When calling "dotnet aws deploy", and choosing an SSO profile, the tool fails with "Unable to create AWS credentials for profile".  If I pass the profile name instead, I get "Failed to get credentials for profile".

If I choose a non-SSO profile instead, the tool proceeds to the next step.

### Reproduction Steps

Attempt to deploy project to AWS via "dotnet aws deploy" command line using an SSO profile.

### Additional Information/Context

We have standardized on using SSO for custom development/deployment to AWS.  

### Version used

1.0.3

### Operating System and version

Windows 10

**Comment by ashovlin** [comment]
Thank you for the report.

We don't include the SSO dependencies from the .NET SDK (which this tool uses under the hood), and we're swallowing the `Assembly AWSSDK.SSOOIDC could not be found or loaded exception` here:
https://github.com/aws/aws-dotnet-deploy/blob/48ef3bc4eef59896c2b17db5b6895fa4c3a575b1/src/AWS.Deploy.CLI/AWSUtilities.cs#L120-L124

I'm not aware of a way to work around it, and have created a ticket tracking this issue in our internal backlog.

**Comment by ashovlin** [comment]
This should be fixed in [version 1.3.7](https://github.com/aws/aws-dotnet-deploy/releases/tag/1.3.7) of the CLI released yesterday.

This hasn't been fixed in the Visual Studio Toolkit yet, but should in a future release when they update the internal version of the deploy tool.

**Comment by ashovlin** [comment]
Per the [Visual Studio Toolkit's changelog](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md#13600-2022-10-12), this should now be addressed in their version 1.36.0.0 and beyond.
