### ISSUE TITLE
Internal Load Balancer Option from CLI (ECS Fargate)

### ISSUE THREAD

**Issue by cbossie** [aws/aws-dotnet-deploy#679]
### Describe the feature

This is a request to include the option for internal or internet-facing load balancer in the "dotnet aws deploy" command advanced settings for Elastic Load Balancer (option 9). The current option is internet facing by default and it is not modifiable via the CLI.

This option would be available only for a new elastic load balancer.

### Use Case

This would enable the deployment of an internal application (e.g. non internet-facing) into a customer's VPC. The default is internet facing, which may not be an acceptable option for some content. Although the user can use and modify a deployment project to achieve this, they currently are not able to specify this setting using the direct CLI.

### Proposed Solution

The solution would be as follows. When creating a new load balancer using the dotnet deployment tool CLI functionality, the default would remain "internet facing", maintaining expectations for users that are already using the tool.

When the user runs "dotnet aws deploy", and selects "3: ASP.NET Core App to Amazon ECS using AWS Fargate" and then types in "more" for Advanced settings, they will select "9" for the elastic load balancer.

The current options look lie the following:
9 . Elastic Load Balancer:
   Create New Load Balancer: True
   Deregistration delay (seconds): 60
   Health Check Path: /
   Health Check Timeout: 5
   Health Check Interval: 30
   Healthy Threshold Count: 5
   Unhealthy Threshold Count: 2

I propose adding an additional option, 'Load Balancer Schema', which would look like one of the following:
"Load Balancer Schema: internet-facing"
or
"Load Balancer Schema: internal"

When the user selects "9" to walk through the settings, if they select "y" for "Create New Load Balancer", then they will have the option to select the load balancer schema. Something like:

Load Balancer Schema:
Do you want the load balancer to be internet facing?
y/n (default y)

Then the rest of parameter selection will proceed as normal.

### Other Information

Ultimately, I believe that this will be a minor-ish change as an update to the ECS Fargate recipe. By adding "internet facing" to the settings object that is consumed in the "ConfigureLoadBalancer" method in the ECS Recipe.cs (https://github.com/aws/aws-dotnet-deploy/blob/main/src/AWS.Deploy.Recipes/CdkTemplates/AspNetAppEcsFargate/Generated/Recipe.cs  -  around line 209), it should be able to override the hard-coded "true" value.

I did a quick test by manually changing that value in the recipe and it appeared to work correctly.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

1.0.3+48ef3bc4ee

### Operating System and version

Tested on Windows 10, but should work on any OS where this is available

**Comment by ashovlin** [comment]
Proposed implementation in https://github.com/aws/aws-dotnet-deploy/pull/706

The underlying CDK construct the deployment tool uses maps `internet-facing`/`internal` to a boolean `internetFacing?`, so the option is slightly different from proposed above.

**Comment by ashovlin** [comment]
The new `Internet-Facing?` option for the ECS Fargate recipe is now available in [release 1.4.10](https://github.com/aws/aws-dotnet-deploy/releases/tag/1.4.10) of the CLI.

This hasn't been released in the VS Toolkit yet, but should appear in an upcoming update.
