### ISSUE TITLE
JSON file definition for deployment setting file links incorrectly?

### ISSUE THREAD

**Issue by wmundev** [aws/aws-dotnet-deploy#688]
### Describe the issue

On the documentation [here](https://aws.github.io/aws-dotnet-deploy/docs/cicd/) , it links the JSON file definition of the "deployment setting file" to [here](https://github.com/aws/aws-dotnet-deploy/tree/main/src/AWS.Deploy.Recipes/RecipeDefinitions)

However, it doesn't look correct to me as from reading about this blog post about the deployment setting file [here](https://aws.amazon.com/blogs/developer/update-new-net-deployment-experience/) , the schema is completely different from the examples provided in the original links

### Links

https://aws.github.io/aws-dotnet-deploy/docs/cicd/

**Comment by philasmar** [comment]
The documentation is explaining that the settings the deployment tool uses, which need to be configured in the `deployment setting file`, can be found at the link [here](https://github.com/aws/aws-dotnet-deploy/tree/main/src/AWS.Deploy.Recipes/RecipeDefinitions). It is not saying that this is the JSON schema of the `deployment setting file`.

**Comment by philasmar** [comment]
I have created a backlog item to track this and add a JSON schema specifically for the deployment settings file.

**Comment by philasmar** [comment]
We have recently updated our documentation and added more details on how to create the deployment settings file https://aws.github.io/aws-dotnet-deploy/docs/cicd/deployment-settings-file/.
The team decided not to move forward with creating a JSON schema and instead we improved our docs.
