### ISSUE TITLE
Deploy to ECS using Fargate fails

### ISSUE THREAD

**Issue by isaacrlevin** [aws/aws-dotnet-deploy#694]
### Describe the bug

Get this error trying to deploy .NET Web Project to ECS using AWS Fargate

> The deployment configuration needs to be adjusted before it can be deployed:
 - Invalid VPC ID. The VPC ID must start with the "vpc-" prefix, followed by either 8 or 17 characters consisting of digits and letters(lower-case) from a to f. For example vpc-abc88de9 is a valid VPC ID.
 - A VPC ID is not specified. Please select a valid VPC ID.

### Expected Behavior

Deploys without issue

### Current Behavior

Throws this error

> The deployment configuration needs to be adjusted before it can be deployed:
 - Invalid VPC ID. The VPC ID must start with the "vpc-" prefix, followed by either 8 or 17 characters consisting of digits and letters(lower-case) from a to f. For example vpc-abc88de9 is a valid VPC ID.
 - A VPC ID is not specified. Please select a valid VPC ID.

### Reproduction Steps

```bash
dotnet new web -o AWSDeployFargate
cd AWSDeployFargate
````
> 3: ASP.NET Core App to Amazon ECS using AWS Fargate
This ASP.NET Core application will be deployed to Amazon Elastic Container Service (Amazon ECS) with compute power managed by AWS Fargate compute engine. If your project does not contain a Dockerfile, it will be automatically generated, otherwise an existing Dockerfile will be used. Recommended if you want to deploy your application as a container image on Linux.

Choose Option 3

### Additional Information/Context

Full CLI 

```bash
dotnet aws deploy
AWS .NET deployment tool for deploying .NET Core applications to AWS.
Project Home: https://github.com/aws/aws-dotnet-deploy

Configuring AWS Credentials using AWS SDK credential search.
Configuring AWS region using AWS SDK region search to us-west-2.
Recommended Deployment Option
-----------------------------
1: ASP.NET Core App to AWS Elastic Beanstalk on Linux
This ASP.NET Core application will be built and deployed to AWS Elastic Beanstalk on Linux. Recommended if you want to deploy your application directly to EC2 hosts, not as a container image.

Additional Deployment Options
------------------------------
2: ASP.NET Core App to AWS Elastic Beanstalk on Windows
This ASP.NET Core application will be built and deployed to AWS Elastic Beanstalk on Windows. Recommended if you do not want to deploy your application as a container image.

3: ASP.NET Core App to Amazon ECS using AWS Fargate
This ASP.NET Core application will be deployed to Amazon Elastic Container Service (Amazon ECS) with compute power managed by AWS Fargate compute engine. If your project does not contain a Dockerfile, it will be automatically generated, otherwise an existing Dockerfile will be used. Recommended if you want to deploy your application as a container image on Linux.

4: ASP.NET Core App to AWS App Runner
This ASP.NET Core application will be built as a container image on Linux and deployed to AWS App Runner, a fully managed service for web applications and APIs. If your project does not contain a Dockerfile, it will be automatically generated, otherwise an existing Dockerfile will be used. Recommended if you want to deploy your web application as a Linux container image on a fully managed environment.

Choose deployment option (recommended default: 1)
3

Name the Cloud Application to deploy your project to
--------------------------------------------------------------------------------
Enter the name of the new CloudFormationStack stack (default AWSDeploy):


Current settings (select number to change its value)
----------------------------------------------------
1. ECS Cluster: AWSDeploy
2. ECS Service Name: AWSDeploy-service
3. Desired Task Count: 3
4. Application IAM Role: *** Create new ***
5. Virtual Private Cloud (VPC):
6. Environment Variables:
7. ECR Repository Name: awsdeploy

Enter 'more' to display Advanced settings.
Or press 'Enter' to deploy:


The deployment configuration needs to be adjusted before it can be deployed:
 - Invalid VPC ID. The VPC ID must start with the "vpc-" prefix, followed by either 8 or 17 characters consisting of digits and letters(lower-case) from a to f. For example vpc-abc88de9 is a valid VPC ID.
 - A VPC ID is not specified. Please select a valid VPC ID.

Please adjust your settings

Current settings (select number to change its value)
----------------------------------------------------
1. ECS Cluster: AWSDeploy
2. ECS Service Name: AWSDeploy-service
3. Desired Task Count: 3
4. Application IAM Role: *** Create new ***
5. Virtual Private Cloud (VPC):
6. Environment Variables:
7. ECR Repository Name: awsdeploy

Enter 'more' to display Advanced settings.
Or press 'Enter' to deploy:
````

### Version used

1.2.4+66fb1e34bb

### Operating System and version

Windows 11

**Comment by philasmar** [comment]
Hello @isaacrlevin, can you describe the VPC situation in your account? Do you have a VPC in the region you are deploying to? if so, is that VPC the default VPC?

**Comment by isaacrlevin** [comment]
I think the issue in my case is that I didn't have a default VPC in that region. To be more clear to customers, we should say exactly that in the error message, or better yet, prompt to create one if one does not exist.

**Comment by philasmar** [comment]
The ECS Fargate recipe should now be able to detect that and switch to creating a new VPC. Can you please update to the latest version of the tool and try again?

**Comment by isaacrlevin** [comment]
That worked!
