### ISSUE TITLE
Elastic Beanstalk deployment is not picking up the configurations from the deployment settings file

### ISSUE THREAD

**Issue by as14692** [aws/aws-dotnet-deploy#695]
### Describe the bug

Get this setting `Application IAM Role: *** Create new ***` after specifying the `RoleArn` for `ApplicationIAMRole `in the deployment settings file. 

Deployment settings file 

```
{
  "ApplicationName": "AppTest2",
  "RecipeId": "AspNetAppElasticBeanstalkLinux",
  "OptionSettingsConfig": {
    "BeanstalkApplication": {
      "CreateNew": true,
      "ApplicationName": "AppTest2"
    },
    "BeanstalkEnvironment": {
      "EnvironmentName": "EnvTest2"
    },
    "EnvironmentType": "LoadBalanced",
    "LoadBalancerType": "application",
    "ApplicationIAMRole": {
      "CreateNew": false,
      "RoleArn": "arn:aws:iam::xxxxxxxxxxxx:role/Admin"
    },
    "InstanceType": "m4.4xlarge"
  }
}
```

### Expected Behavior

Deploys the application to Elastic Beanstalk with the specified configurations in the deployment settings file

### Current Behavior

```
dotnet aws deploy --apply DeploymentConfigFile.json -d

AWS .NET deployment tool for deploying .NET Core applications to AWS.
Project Home: https://github.com/aws/aws-dotnet-deploy

Configuring AWS Credentials using AWS SDK credential search.
Configuring AWS region using AWS SDK region search to us-west-2.

Configuring Recommendation with: 'ASP.NET Core App to AWS Elastic Beanstalk on Linux'.

Current settings (select number to change its value)
----------------------------------------------------
1. Elastic Beanstalk Application: AppTest2
2. Environment Name:
        Environment Name: AppTest2-dev
3. Environment Type: SingleInstance
4. Application IAM Role: *** Create new ***
5. Service IAM Role: *** Create new ***
6. Environment Variables:
```

### Reproduction Steps

`dotnet aws deploy --apply DeploymentConfigFile.json`

### Additional Information/Context

The application deploys successfully with the specified Application IAM Role while using Visual Studio **Publish to AWS...** option

### Version used

1.0.3+48ef3bc4ee

### Operating System and version

Windows 10

**Comment by 96malhar** [comment]
@as14692 As part of releasing the public version of this tooling, we introduced a breaking change in the settings file schema that renamed the `OptionSettingsConfig` property to `Settings`. https://github.com/aws/aws-dotnet-deploy/pull/631

Please rename the property in your deployment settings file and try again. We will soon prioritize improving the documentation on how to create the deployment settings file.

**Comment by as14692** [comment]
Thanks @96malhar! It works for Linux deployment. However when I make the same change in the deployment settings file for **AspNetAppElasticBeanstalkWindows** recipe as given below, I get the following message
```
The Option Setting Item BeanstalkEnvironment does not exist as part of the ASP.NET Core App to AWS Elastic Beanstalk on Windows recipe

For more information, please visit our troubleshooting guide https://aws.github.io/aws-dotnet-deploy/troubleshooting-guide/.
If you are still unable to solve this issue and believe this is an issue with the tooling, please cut a ticket https://github.com/aws/aws-dotnet-deploy/issues/new/choose.
```

Deployment settings file for Windows
```
{
  "ApplicationName": "AppTest2",
  "RecipeId": "AspNetAppElasticBeanstalkWindows",
  "Settings": {
    "BeanstalkApplication": {
      "CreateNew": true,
      "ApplicationName": "AppTest2"
    },
    "BeanstalkEnvironment": {
      "EnvironmentName": "EnvTest2"
    },
    "EnvironmentType": "LoadBalanced",
    "LoadBalancerType": "application",
    "ApplicationIAMRole": {
      "CreateNew": false,
      "RoleArn": "arn:aws:iam::xxxxxxxxxxxx:role/Admin"
    },
    "InstanceType": "m4.4xlarge"
  }
}

```

**Comment by 96malhar** [comment]
You need to use the `EnvironmentName` instead of `BeanstalkEnvironment` whne using `AspNetAppElasticBeanstalkWindows`

```
{
  "ApplicationName": "AppTest2",
  "RecipeId": "AspNetAppElasticBeanstalkWindows",
  "Settings": {
    "BeanstalkApplication": {
      "CreateNew": true,
      "ApplicationName": "AppTest2"
    },
    "EnvironmentName": "EnvTest2",
    "EnvironmentType": "LoadBalanced",
    "LoadBalancerType": "application",
    "ApplicationIAMRole": {
      "CreateNew": false,
      "RoleArn": "arn:aws:iam::xxxxxxxxxxxx:role/Admin"
    },
    "InstanceType": "m4.4xlarge"
  }
}

``` 

See [here](https://github.com/aws/aws-dotnet-deploy/blob/66fb1e34bbea10bbd995596e1eec801b79ff9102/src/AWS.Deploy.Recipes/RecipeDefinitions/ASP.NETAppElasticBeanstalkWindows.recipe#L209) for the recipe file

**Comment by as14692** [comment]
Works, thank you.
