### ISSUE TITLE
Error while publishing docker image to ecr repository

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-dotnet-deploy#754]
Creating an issue on our repo to track https://github.com/aws/aws-toolkit-visual-studio/issues/320 on the Visual Studio Toolkit. 

This Docker login step is handled within the Deploy Tool (this repo). If there is a bug to fix, the fix would have to originate in this repository.

```
Pushing the docker image to ECR repository...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: error storing credentials - err: exit status 1, out: The stub received bad data.``

wanotif1balisoketcom could not be published as ASP.NET Core App to Amazon ECS using AWS Fargate: Failed to login to Docker due to the following reason:
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: error storing credentials - err: exit status 1, out: The stub received bad data.``

wanotif1.balisoket.com failed to publish to AWS.
```

### Version used

UNKNOWN

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Replied to user on the other issue in toolkit repo. Perhaps this needs reproduction with restricted credentials and then deploy using the tool.

**Comment by ashishdhingra** [comment]
Issue with similar error is reported at https://github.com/aws/aws-cli/issues/5636.

**Comment by ashishdhingra** [comment]
Responded to user on https://github.com/aws/aws-toolkit-visual-studio/issues/320#issuecomment-1463034048

**Comment by ashishdhingra** [comment]
Related issue https://github.com/aws/aws-toolkit-visual-studio/issues/320 closed as stale.
