### ISSUE TITLE
Deploy Tool Hangs Indefinitely When Docker Hangs

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-dotnet-deploy#786]
### Describe the bug

I'm trying to deploy a new application, but the deploy tool is hanging indefinitely here:

```
Choose deployment option (recommended default: 1)
3

Name the Cloud Application to deploy your project to
--------------------------------------------------------------------------------
Enter the name of the new CloudFormationStack stack (default WebAppWithDockerFile):
```

### Expected Behavior

Deployment to proceed

### Current Behavior

Upon investigation, the `docker info` we're running is hanging indefinitely as well

https://github.com/aws/aws-dotnet-deploy/blob/52f2ff48986a99f824ffcbd8b64beaa04452aed6/src/AWS.Deploy.Orchestration/SystemCapabilityEvaluator.cs#L51-L61

### Reproduction Steps

Unsure why my Docker installation is stuck, it seems like Docker can hang for multiple reasons: https://github.com/docker/cli/issues/3433

It resolved itself once I did a factory reset of Docker Desktop.

### Possible Solution

The deploy tool should be more resilient (set timeout on the child processes?) and display a helpful error message. For both `docker info` and `node --version`, I'd think we expect these to complete within a couple seconds.

### Version used

1.14.6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Needs review. Makes sense to have a timeout for the child processes to return.

**Comment by ashovlin** [comment]
Fixed in https://github.com/aws/aws-dotnet-deploy/releases/tag/1.21.13 via #837
