### ISSUE TITLE
Add support for deploying .NET 6 applications to Amazon Linux 2023 Beanstalk platforms

### ISSUE THREAD

**Issue by shruti0085** [aws/aws-dotnet-deploy#806]
### Describe the feature

Creating an issue here to track https://github.com/aws/aws-toolkit-visual-studio/issues/371#issuecomment-1819465803 on the Visual Studio Toolkit.
The Visual Studio Toolkit wraps the .NET Deployment Tool, so any changes to behavior will have to originate in this repository.

Deploy tool does not support deploying to Beanstalk platforms of Amazon Linux 2023 today. The latest platform version as of(12/4/2023) for .NET 6 project is `.NET Core Running on 64 bit Amazon Linux 2 V2.6.2`

### Use Case

Snippet from the feature-request
I encountered the same behavior and compared a working case to a non-working case. I noted that the non working case was using Linux 2023 as opposed to Linux 2... Linux 2023 environment is new default behavior, via the AWS create environment wizard. I tried creating a new environment using ".NET Core running on 64bit Amazon Linux 2/2.6.2" and that worked. I also tried creating an environment via the AWS toolkit and noted that the created environment was Linux 2, supporting my suspicion that this version of the AWS toolkit is not supporting Linux 2023.

### Proposed Solution

Add support for deploying to Beanstalk platforms for Amazon Linux 2023 with the deploy tool

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

1.16.7

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Needs review with the team for prioritization.

**Comment by ashovlin** [comment]
This has been addressed in https://github.com/aws/aws-dotnet-deploy/releases/tag/1.18.6.
