### ISSUE TITLE
Add support for LaunchTemplates in aws-dotnet-deploy tool. LaunchConfigurations are not supported anymore

### ISSUE THREAD

**Issue by chitikjb** [aws/aws-dotnet-deploy#877]
### Describe the bug

Starting on October 1, 2024, new accounts will not be able to create new launch configurations by using the console, API, CLI, and CloudFormation. https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-config.html

This created an issue when I used aws-dotnet-deploy tool in my devops pipeline to deploy a .NET 8 webAPI to elastic beanstalk (linux) environment in a brand new AWS account. Currently the tool only supports LaunchConfiguration and not LaunchTemplates, that causes the issue.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The deployment to go smoothly

### Current Behavior

The deployment fails because LaunchConfigurations are not supported anymore in new aws accounts and the tool uses LaunchConfigurations in it's autoscaling group for load balanced EB deployments.

### Reproduction Steps

use aws-dotnet-deploy tool to deploy a .NET 8 Web application/WebAPI to a load balanced Elastic Beanstalk environment.

### Version used

1.26.1

### Operating System and version

Amazon Linux 2

**Comment by ashishdhingra** [comment]
Yes, this is something that we should address.

**Comment by bhoradc** [comment]
The changes are addressed in Pull Request #877. Marking as completed.
